Major untracked updates

diff --git a/ros4nix b/ros4nix
--- a/ros4nix
+++ b/ros4nix
@@ -199,6 +199,64 @@ load_units () {
     sudo systemctl start multi-user.target
 }
 
+# Bootstrap an Ubuntu installation into /var/ros using Docker if
+# necessary.
+bootstrap_check () {
+    if [ $(uname -r | cut -d. -f3) -le 255 ]; then
+        # System is OK.
+        return
+    fi
+
+    echo "Kernel is so badly misconfigured bootstrapping an Ubuntu"
+    echo "installation is impossible. I'm going to ask Docker to do"
+    echo "it instead."
+    echo
+    echo "WARKING: At the moment this ONLY works for Ubuntu Focal."
+
+    if type docker > /dev/null && \
+            [ -e /etc/apt ] && \
+            ! [ -e /etc/apt/sources.list.d/docker.list ]; then
+        echo "Docker is installed, but it's done wrong."
+
+        sudo apt-get remove docker docker-engine docker.io containerd runc || true
+    fi
+
+    if ! type docker > /dev/null; then
+        echo "Docker isn't installed."
+
+        echo -n 'Would you like me to install it for you [yN]?'
+        read input
+        if [ "${input,,?}" != "y" ]; then
+            echo 'Aborting.'
+            return 1
+        fi
+
+        sudo apt-get update
+        sudo apt-get install \
+             ca-certificates \
+             curl \
+             gnupg \
+             lsb-release
+
+        sudo mkdir -p /etc/apt/keyrings
+
+        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
+
+        echo \
+            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
+            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+
+        sudo apt-get update
+
+        sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
+    fi
+
+    echo "Docker looks like it's installed and working."
+    echo
+
+    sudo docker run -it --rm --volume /var/ros:/tmp/var ubuntu:focal /bin/sh -c 'TODO'
+}
+
 if [ "$#" = 0 ]; then
     print_help
     exit 1
